### ISSUE TITLE
nmod:poss or det for possessive

### ISSUE THREAD

**Issue by laurenCassidy** [UniversalDependencies/UD_Irish-IDT#150]
Wondering if possessives (mo, do, a, ár, bhur) should be `det` as opposed to` nmod:poss`?

**Comment by tlynn747** [comment]
It's an option.Thanks for the link to that thread @kscanne 

Would you guys be open to det:poss ?

https://universaldependencies.org/it/dep/det-poss.html

What prompted the need for change @laurenCassidy? Did something crop up in the Twitter treebank?

**Comment by rueter** [comment]
@laurenCassidy this is a very interesting question from dealing with Finno-Ugric languages.
>Wondering if possessives (mo, do, a, ár, bhur) should be det as opposed to nmod:poss?

The Finnish TDT answer to a similar question (minun 1Sg:Gen, sinun 2Sg:Gen, hänen 3Sg:Gen, sen Dem:Sg:Gen, meidän 1Pl:Gen, teidän 2Pl:Gen, heidän 3Pl:Gen) is nmod:poss. Their reasoning, it would seem, is that the genitive-case pronoun would have a parallel in the genitive case noun.
Hence
>nmod:poss(nimi, sen) 'its name'
>nmod:poss(nimi, projektin) 'project's name'
>nmod:poss(nimensä, hänen) 'his/her<+human> name'
>nmod:poss(nimi, pojan) 'boy's name'

In Finnish we are talking about a genitive personal pronoun, a genitive demonstrative pronoun. These pronouns share no common traits with adjectives, as it were, since Finnish adjectives would take the same case as their head words.

In the Estonian analogical contexts the personal pronouns are also in the genitive as are the nouns. Estonian, however, only uses the nmod-relation.

Turkish, it seems, uses the nmod:poss relation for both pronouns and nouns.  @jonorthwash can you tell us the situation in Kazakh.

My question for you @laurenCassidy @tlynn747 @kscanne is the following:
are the pronouns (mo, do, a, ár, bhur) parallels of genitive-case nouns, i.e., are they simply genitive forms that do not change like an adjective? Do (mo, do, a, ár, bhur) change form according to the gender of the noun they modify?

**Comment by laurenCassidy** [comment]
>What prompted the need for change @laurenCassidy? Did something crop up in the Twitter treebank?

I was consulting the annotation guidelines and wondered why the possessive pronouns were considered `nmod:poss` when the POS-tag is DET. 

>are the pronouns (mo, do, a, ár, bhur) parallels of genitive-case nouns, i.e., are they simply genitive forms that do not change like an adjective? Do (mo, do, a, ár, bhur) change form according to the gender of the noun they modify?

It seems that possessive pronouns derive from genitive-case personal pronouns.

> Do (mo, do, a, ár, bhur) change form according to the gender of the noun they modify?
They do not inflect.

>https://github.com/UniversalDependencies/docs/issues/477
Thank you for linking this discussion - I will check it out

**Comment by tlynn747** [comment]
Updated to det:poss to reflect Italian treebank approach (English uses `nmod:poss`, Spanish uses `det`)
