### ISSUE TITLE
Comprehensive use of Typo=Yes

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#39]
I can pretty easily add this feature across the treebank with some help from my proofing tools. Patch coming... about 100 examples.

In terms of annotation guidelines going forward, it can be subtle to decide if a given non-standard spelling is a legitimate dialect or historical spelling, or if it's really an error.  I think it's best to restrict the use of Typo=Yes to the latter.

**Comment by tlynn747** [comment]
This relates again to the decisions around UGC content in our article on treebanking UGC: 

Treebanking User-Generated Content
A UD Based Overview of Guidelines, Corpora and Unified Recommendations
https://arxiv.org/pdf/2011.02063.pdf

See Section 4.5 re the use of the MISC column. Instead of Type=No (when it's not a typo), there's a selection of options for non canonical spelling (NonCan=X), that arises from phenomena such as spelling variation (SpellVar), contraction (Cont), Character omission (CharOm), transliteration (Transl) etc. 

Can this automatic approach account for this?

**Comment by kscanne** [comment]
It would be easy enough to write something to classify examples into categories like these, but at the scale we're talking about it's probably faster for me to manually label.

What I might do is start with what I consider Typo=Yes examples for this issue since those are relatively easy.  In that case, my plan is to correct the spelling in the LEMMA column, which agrees with your recommendation in Table 3. I can include a CorrectForm feature under MISC also.

I see you have diacritic omission separate from spelling error in the table.  I'd recommend including Typo=Yes for diacritic errors as well; there's a bunch of these in the treebank: coimead, coinnioll, diospóid, earraid, gniomhú, etc. Does that seem reasonable? Would seem strange to view these as somehow different from typos resulting from an added or moved diacritic (aistríú, deán, etc.).
