### ISSUE TITLE
Tag PROPN where needed and clarify features for PROPN

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#49]
There are quite a few proper names labeled as NOUN.  Those are easy for me to fix.

Before I do, I want to clarify what the features should be. It looks like features "Gender=Masc|Number=Sing" were added to many PROPN tokens, even ones that are probably better labeled "Foreign=Yes" or left without features entirely (e.g. "Merrill" or "Lynch"). 

Related, I see tokens like "Mary" which are PROPN but get Gender=Fem.  For people, do you want to assign gender based on the presumed gender of the referent, even if the word/name is not "Irish"?

**Comment by tlynn747** [comment]
Good questions...

I believe we're staying away from Foreign=Yes for names. In the same was as we don't use the flat:foreign label for name strings. See the end of section 3 in the MWE paper: https://www.aclweb.org/anthology/2020.udw-1.15.pdf

As for gender, I've looked across a few language treebanks and there are mixed approaches to it. Two of the Spanish treebanks mark gender (e.g. Kori Schulman, Obama, Joe Sternlieb, Michael Fallon).  Some French treebanks also mark gender on foreign names (e.g. Brian Eno - FR_Sequoia; Kori - FR_PUD, Juan Jesus - FR_FQB)
Due to the nature of the "bilingual" society, many of the names in Irish data are "English" so I think we should treat them in the same way we treat Irish names. 
But I don't think gender features can apply to surnames.

I'm going to be working on proper noun strings for the the next week or two. I'm reviewing the use of flat for strings that are compositional and have internal syntax, and should be parsed appropriately. See the last paragraph under "flat" in section 3.3 in above paper. We'l be capturing named-entity info in the MISC column for those that I removed "flat" labelling from.

Go ahead and make your changes... I'm going to look for patterns in the meantime to help me automate :)

**Comment by kscanne** [comment]
This is great, thanks.  A couple of addenda as you're thinking about this... I could imagine cases where keeping the gender information could be useful linguistically, e.g. do Irish speakers say "Treasa bhocht!" but "Teresa bocht!", that sort of thing.  Similarly with "Irish" vs "non-Irish". There was discussion on Twitter this week about if you say "A Kevin, a chara" or "Kevin, a chara" (or even "A Khevin"). Same for placenames...  I was in touch with a linguistics PhD student who was looking at how initial mutations behave for Irish placenames vs. non-Irish places names ("i mBarcelona" or "in Barcelona").

I would be good to include genders on traditional Irish surnames at least, which are usually masculine+genitive ("Gabhann" in Mac Gabhann, etc.). I was going to raise this in a separate issue.  Mac, Ó, Ní, Uí, etc. are currently PART.  In cases like "saothar Choimisiún Uí Bhrolcháin" in sentence 1973 it is grammatically nmod, nmod, nmod.  I don't mind the flat:name, but I think the Uí here should have a genitive feature, Ó (or ó) as its lemma, and connect to "Choimisiún" as nmod (currently flat). Many similar cases.

For now, since you'll be looking at PROPN this week, I'll just flip the 40 or so names that I see from NOUN to PROPN so they'll be on your radar.

**Comment by kscanne** [comment]
Close this and will raise the personal name business in a separate, low-priority issue
