### ISSUE TITLE
Days of the week and months

### ISSUE THREAD

**Issue by kscanne** [UniversalDependencies/UD_Irish-IDT#75]
The Irish guidelines (https://universaldependencies.org/ga/pos/PROPN.html) say that days of the week and months should be tagged NOUN not PROPN, but they're PROPN most of the time in the treebank. More specifically in the case of days, "Dé" is labeled NOUN in most cases, but Máirt, Céadaoin, etc. get PROPN.  Can I relabel all of these as NOUN?  Or do you want to switch to PROPN and update the guidelines?

**Comment by tlynn747** [comment]
I'm not attached to this either way. The rational behind the PROPN was because we were regarding them as proper noun strings, ie flats. Some instances of Dé are PROPN in Elaine's corpus so that might have triggered it off re days. 
But after checking several treebanks, PROPN v NOUN tagging for days of the week seems to vary, even within language groups. 

So happy for the change if it helps parsing in any way.

**Comment by kscanne** [comment]
These are tricky. I went with PROPN across the board, but a bit like the language names these don't coincide perfectly with Definite=Def in general (the month looks definite in "tús mhí Eanáir", but not in "an crann Nollag").
