### ISSUE TITLE
PPs attached to verbal nouns: nmod or obl?

### ISSUE THREAD

**Issue by colinbatchelor** [UniversalDependencies/UD_Irish-IDT#91]
In train, sentence 915, _ag obair air son saoirse_, the deprel for _saoirse_ is `obl`.
In train, sentence 938, _ag fógairt mar 'phacáiste'_, the deprel for _phacáiste_ is `nmod`.

Is there a pattern I've missed?

**Comment by kscanne** [comment]
Should be `obl`.  A quick scan shows quite a few others that should be corrected. I manually checked sentences 1000-1100 and see problems in sentences 1001, 1014, 1016, 1017, 1058.  Probably need to be checked by hand across the full treebank since the VerbForm features aren't always reliable e.g. on words like "ordú" when it means "an order"; here an nmod would be fine.

**Comment by tlynn747** [comment]
Thanks for pointing out Colin.

The treebank is a work-in-progress and still many bugs to clean up.  As Kevin said a PP attachment to a Verbal Noun should be obl
